#!/usr/bin/env python3
"""Generate Kotlin from the iOS-owned, manifest-pinned Unicode property fixture."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
fixture = json.loads((ROOT / 'fixtures/unicode/grapheme-properties-16.0.0.json').read_text())
assert fixture['unicodeVersion'] == '16.0.0'
ranges = fixture['ranges']
output = ROOT / 'nuxie-android/src/main/kotlin/ai/nuxie/sdk/presentation/UnicodeGraphemeProperties.kt'
lines = ['package ai.nuxie.sdk.presentation', '',
         '// Generated by scripts/generate-grapheme-tables.py from Unicode 16.0.0.',
         '// Unicode data license: src/main/resources/META-INF/LICENSE-unicode.txt.',
         'internal object UnicodeGraphemeProperties {',
         '    fun get(codepoint: Int): Int {',
         '        if (codepoint in 0xAC00..0xD7A3) return if ((codepoint - 0xAC00) % 28 == 0) 12 else 13',
         '        var low = 0', '        var high = ranges.size / 3 - 1',
         '        while (low <= high) {', '            val mid = (low + high) ushr 1',
         '            val offset = mid * 3', '            when {',
         '                codepoint < ranges[offset] -> high = mid - 1',
         '                codepoint > ranges[offset + 1] -> low = mid + 1',
         '                else -> return ranges[offset + 2]',
         '            }', '        }', '        return 0', '    }', '',
         '    private val ranges = intArrayOf(']
lines.extend(f'        0x{start:X}, 0x{end:X}, {value},' for start, end, value in ranges)
lines.extend(['    )', '}', ''])
output.write_text('\n'.join(lines))
print(f'Generated {len(ranges)} Unicode 16.0.0 property ranges')
