#!/usr/bin/env python3
"""Generate the existing fixture against the caller's selected runtime schema."""

import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[2]
EXPECTED_SHA256 = "fe28bef78da518159aaed81de8007feff6d56a783024d87b1c1dc6c8c6d3f7e1"
ASSET = ROOT / "nuxie-android/src/androidTest/assets/semantic_text.riv"


def workspace(runtime):
    if not (runtime / "MODULE.bazel").is_file() or not (runtime / "crates/nuxie-schema/BUILD.bazel").is_file():
        raise ValueError("Selected runtime checkout has no Bazel schema interface; use its Bazel migration branch without changing this SDK's artifact pin")
    directory = ROOT / "build/semantic-fixture"
    directory.mkdir(parents=True, exist_ok=True)
    contents = {
        "MODULE.bazel": 'module(name = "nuxie_android_semantic_fixture")\n'
                        'bazel_dep(name = "nuxie_runtime", version = "0.1.0")\n'
                        'bazel_dep(name = "rules_rust", version = "0.74.0")\n'
                        'local_path_override(module_name = "nuxie_runtime", path = ' + json.dumps(str(runtime)) + ')\n',
        "BUILD.bazel": 'load("@rules_rust//rust:defs.bzl", "rust_binary")\n'
                       'rust_binary(name = "generate", srcs = ["semantic-text.rs"], crate_root = "semantic-text.rs", '
                       'edition = "2021", deps = ["@nuxie_runtime//crates/nuxie-schema:nuxie-schema__host"])\n',
        ".bazelversion": (ROOT / ".bazelversion").read_text(),
    }
    for name, content in contents.items():
        path = directory / name
        if not path.is_file() or path.read_text() != content:
            path.write_text(content)
    source = directory / "semantic-text.rs"
    if not source.is_symlink():
        source.symlink_to(ROOT / "scripts/fixtures/semantic-text.rs")
    return directory


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("runtime", type=Path, nargs="?", default=ROOT / "../../third_party/nuxie-runtime")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    runtime = args.runtime.resolve(strict=True)
    directory = workspace(runtime)
    candidate = os.environ.get("NUXIE_BAZEL_BIN") or shutil.which("bazelisk") or shutil.which("bazel")
    if not candidate:
        parent = ROOT.parent.parent / "node_modules/.bin/bazelisk"
        if parent.is_file():
            candidate = str(parent)
    if shutil.disk_usage(directory).free < 5 * 1024**3:
        raise ValueError("Fixture compilation needs at least 5 GiB of free disk")
    command = [candidate] if candidate else [sys.executable, str(ROOT / "scripts/bazel/launcher.py")]
    user_root = os.environ.get("NUXIE_BAZEL_OUTPUT_USER_ROOT")
    if user_root:
        if not Path(user_root).is_absolute():
            raise ValueError("NUXIE_BAZEL_OUTPUT_USER_ROOT must be absolute")
        command.append("--output_user_root=" + user_root)
    jobs = os.environ.get("NUXIE_BAZEL_JOBS", "2")
    if not jobs.isdecimal() or int(jobs) < 1:
        raise ValueError("NUXIE_BAZEL_JOBS must be a positive integer")
    with tempfile.TemporaryDirectory(prefix="nuxie-semantic-fixture-") as temporary:
        generated = Path(temporary) / "semantic_text.riv"
        subprocess.run(command + ["run", "--jobs=" + jobs, "//:generate", "--", str(generated)], cwd=directory, check=True)
        data = generated.read_bytes()
        if hashlib.sha256(data).hexdigest() != EXPECTED_SHA256:
            raise ValueError("Selected runtime changed the recorded semantic fixture bytes; the build migration does not update fixtures")
        if args.check:
            if ASSET.read_bytes() != data:
                raise ValueError("Checked-in semantic fixture differs from its generated bytes")
        elif ASSET.read_bytes() != data:
            ASSET.write_bytes(data)
    print("Semantic fixture matches the recorded SHA-256")


if __name__ == "__main__":
    try:
        main()
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        print(f"error: {error}", file=sys.stderr)
        sys.exit(1)
