package ai.nuxie.sdk.presentation

import ai.nuxie.sdk.runtime.NuxiePlayerPointerEvent
import ai.nuxie.sdk.runtime.NuxiePlayerPointerKind
import ai.nuxie.sdk.runtime.NuxieRuntime
import ai.nuxie.sdk.runtime.NuxieTextGeometryCapture
import ai.nuxie.sdk.runtime.NuxieRuntimeCallException
import androidx.test.platform.app.InstrumentationRegistry
import kotlinx.serialization.json.*
import org.junit.Assert.*
import org.junit.Test
import java.security.MessageDigest

/** Runs publisher-generated bytecode through the same owned player used by ExperienceSurfaceHost. */
class GeneratedInteractionPlayerDeviceTest {
    @Test fun publishedActionRunsBesideTheAuthoredSceneExactlyOnce() {
        val runtime = NuxieRuntime.shared
        assertTrue(runtime.isAvailable)
        val assets = InstrumentationRegistry.getInstrumentation().context.assets
        fun json(path: String) = assets.open(path).bufferedReader().use { Json.parseToJsonElement(it.readText()).jsonObject }
        val contract = json("sdk/interaction-player.json").getValue("published").jsonObject
        val bytes = assets.open(contract.getValue("fixture").jsonPrimitive.content).use { it.readBytes() }
        val provenance = json("runtime/screen-control/provenance.json")
        assertEquals(provenance.getValue("sha256").jsonPrimitive.content,
            MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) })
        val renderer = checkNotNull(runtime.newAndroidVulkanRenderer(390, 844))
        try {
            val file = checkNotNull(runtime.importFile(renderer, bytes, checkNotNull(runtime.inspectFileAssets(bytes))))
            try {
                fun exercise(experience: Boolean, missingGeometry: Boolean = false): Pair<List<String>, ByteArray> {
                    val artboardName = contract.getValue("artboard").jsonPrimitive.content
                    val artboard = checkNotNull(file.newArtboard(artboardName))
                    try {
                        val player = if (experience) file.newExperiencePlayer(artboard, artboardName) else checkNotNull(artboard.newPlayer())
                        try {
                            player.stepTyped(elapsedSeconds = 0.0)
                            val initial = renderer.renderToCpuFrame(player, 0xff000000.toInt(), true).rgba
                            val position = contract.getValue("pointer").jsonObject
                            fun pointer(kind: NuxiePlayerPointerKind) = NuxiePlayerPointerEvent(kind,
                                position.getValue("x").jsonPrimitive.float, position.getValue("y").jsonPrimitive.float, 1, 0f)
                            val requestedRuns = if (missingGeometry) listOf("missing geometry run") else emptyList()
                            val down = player.stepTyped(elapsedSeconds = 0.0, pointers = listOf(pointer(NuxiePlayerPointerKind.DOWN)), textRunNames = requestedRuns)
                            val up = player.stepTyped(elapsedSeconds = 0.0, pointers = listOf(pointer(NuxiePlayerPointerKind.UP)), textRunNames = requestedRuns)
                            if (missingGeometry) {
                                assertEquals(NuxieTextGeometryCapture.Failed(3), down.textGeometry)
                                assertEquals(NuxieTextGeometryCapture.Failed(3), up.textGeometry)
                            }
                            assertTrue(player.stepTyped(elapsedSeconds = 0.25).hostCommands.isEmpty())
                            return (down.hostCommands + up.hostCommands).map { it.name } to initial
                        } finally { player.close() }
                    } finally { artboard.close() }
                }
                val default = exercise(false)
                val experience = exercise(true)
                assertEquals(contract.getValue("defaultHostCommands").jsonArray.map { it.jsonPrimitive.content }, default.first)
                assertEquals(contract.getValue("experienceHostCommands").jsonArray.map { it.jsonPrimitive.content }, experience.first)
                assertEquals("Geometry failure preserves exactly-once authored commands", experience.first,
                    exercise(true, missingGeometry = true).first)
                assertArrayEquals("Adding generated interaction must preserve initial authored pixels", default.second, experience.second)
            } finally { file.close() }
        } finally { renderer.close() }
    }
    @Test fun failedCompiledActionRejectsPartialEffectsAndRetiresItsOccurrence() {
        val runtime = NuxieRuntime.shared
        assertTrue(runtime.isAvailable)
        val assets = InstrumentationRegistry.getInstrumentation().context.assets
        val contract = assets.open("sdk/interaction-player.json").bufferedReader().use {
            Json.parseToJsonElement(it.readText()).jsonObject.getValue("scriptFailure").jsonObject
        }
        val bytes = assets.open(contract.getValue("fixture").jsonPrimitive.content).use { it.readBytes() }
        val renderer = checkNotNull(runtime.newAndroidVulkanRenderer(390, 844))
        try {
            val file = checkNotNull(runtime.importFile(renderer, bytes, checkNotNull(runtime.inspectFileAssets(bytes))))
            try {
                // Reuse the imported file after failure, but allocate a new occurrence.
                repeat(2) {
                    val name = contract.getValue("artboard").jsonPrimitive.content
                    val artboard = checkNotNull(file.newArtboard(name))
                    try {
                        val player = file.newExperiencePlayer(artboard, name)
                        try {
                            assertTrue(player.stepTyped(elapsedSeconds = 0.0).hostCommands.isEmpty())
                            val position = contract.getValue("pointer").jsonObject
                            fun pointer(kind: NuxiePlayerPointerKind) = NuxiePlayerPointerEvent(kind,
                                position.getValue("x").jsonPrimitive.float, position.getValue("y").jsonPrimitive.float, 1, 0f)
                            assertTrue(player.stepTyped(elapsedSeconds = 0.0,
                                pointers = listOf(pointer(NuxiePlayerPointerKind.DOWN))).hostCommands.isEmpty())
                            val failure = assertThrows(NuxieRuntimeCallException::class.java) {
                                player.stepTyped(elapsedSeconds = 0.0, pointers = listOf(pointer(NuxiePlayerPointerKind.UP)))
                            }
                            assertEquals(contract.getValue("nativeStatus").jsonPrimitive.int, failure.status)
                            assertThrows(IllegalStateException::class.java) { player.requireHandle() }
                            assertThrows(IllegalStateException::class.java) { player.stepTyped(elapsedSeconds = 0.0) }
                        } finally { player.close() }
                    } finally { artboard.close() }
                }
            } finally { file.close() }
        } finally { renderer.close() }
    }

}
